name: Build resume variants
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role: [Resume, Admin, DataEngineer, MLE]

    steps:
      - uses: actions/checkout@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install TeX Live + latexmk
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            texlive-latex-extra \
            texlive-fonts-extra \
            texlive-fonts-recommended \
            latexmk
      - name: Build resume (${{ matrix.role }})
        run: bash template/build.sh ${{ matrix.role }}

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: Resume_${{ matrix.role }}
          path: output/*${{ matrix.role }}*.pdf

  commit:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull PDFs from artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: output/Resume_*
          merge-multiple: true

      - name: Commit & push
        run: |
          ls -l .
          ls -l output

          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/*.pdf
          git diff --cached --quiet && echo "no changes" && exit 0
          git commit -m "CI: update resume PDFs [skip ci]"
          git push origin HEAD