name: Build résumé variants
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role: [de, mle] # [default, de, mle, ds, admin]

    steps:
      - uses: actions/checkout@v4

      - name: Install TeX Live + latexmk
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y texlive-latex-extra latexmk

      - name: Build résumé (${{ matrix.role }})
        run: bash template/build_resume.sh ${{ matrix.role }}

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume-${{ matrix.role }}
          path: output/resume_${{ matrix.role }}.pdf
