name: Build all resume variants
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role: [de, mle] # [default, de, mle, ds, admin]

    steps:
      - uses: actions/checkout@v4

      - name: Compile (${{ matrix.role }})
        uses: xu-cheng/latex-action@v2
        with:
          pre_compile: |
            cat <<'EOF' > build.tex
            \input{roles/${{ matrix.role }}.tex}
            \input{template/resume.tex}
            EOF
          root_file: build.tex
          args: -pdf -silent -jobname=resume_${{ matrix.role }}
          post_compile: latexmk -c   # wipe aux, log, fls
          
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume-${{ matrix.role }}
          path: resume_${{ matrix.role }}.pdf
